POST http://localhost:8001/user/addUser HTTP/1.1
content-type: application/json

{
"username": "xxxx",
"email": "xxxx",
"password": "xxxx",
"role": "Doctor"
}

###
POST http://localhost:8001/user/addDoctorToContact HTTP/1.1
content-type: application/json

{
"username": "Patient 1",
"doctor": "Docteur 1"
}